const FIELDS=[
 {k:'numero',n:'Nº do informe',a:['nº do informe','no do informe','n do informe','numero do informe','nº informe'],req:true},
 {k:'tipo',n:'Tipo de registro',a:['tipo de registro','tipo registro'],req:true},
 {k:'local',n:'Local/Área',a:['local/área','local/area','local','área','area'],req:true},
 {k:'data',n:'Data',a:['data','data do registro','data ocorrência','data da ocorrência'],req:true},
 {k:'semana',n:'Semana',a:['semana','nº semana','numero da semana']},
 {k:'informante',n:'Informante',a:['informante','nome do informante'],req:true},
 {k:'descricao',n:'Descrição da ocorrência',a:['descrição da ocorrência','descricao da ocorrência','descrição','descricao'],req:true},
 {k:'acao',n:'Plano de ação',a:['plano de ação','plano de acao','ação','acao']},
 {k:'responsavel',n:'Responsável',a:['responsável','responsavel']},
 {k:'lideranca',n:'Liderança',a:['liderança','lideranca']},
 {k:'severidade',n:'Severidade / Potencial',a:['severidade','potencial','potencialidade']},
 {k:'previsto',n:'Previsto',a:['previsto','data prevista','prazo']},
 {k:'realizado',n:'Realizado',a:['realizado','data realizado','data de realização']},
 {k:'status',n:'Status',a:['status','situação','situacao']}
];
const S={source:null,template:null,swb:null,twb:null,rows:[],headers:[],map:{},targets:{},tSheet:null,logos:{kaefer:null,gerdau:null}};
const DB_NAME='informes-config-v1',DB_STORE='files';
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>r.result.createObjectStore(DB_STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbPut(key,value){const db=await openDB();return new Promise((resolve,reject)=>{const t=db.transaction(DB_STORE,'readwrite');t.objectStore(DB_STORE).put(value,key);t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error)})}
async function dbGet(key){const db=await openDB();return new Promise((resolve,reject)=>{const t=db.transaction(DB_STORE,'readonly');const r=t.objectStore(DB_STORE).get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbClear(){const db=await openDB();return new Promise((resolve,reject)=>{const t=db.transaction(DB_STORE,'readwrite');t.objectStore(DB_STORE).clear();t.oncomplete=resolve;t.onerror=()=>reject(t.error)})}
async function saveLocalConfig(){const tf=$('defaultTemplate').files[0],kf=$('defaultKaefer').files[0],gf=$('defaultGerdau').files[0];if(tf)await dbPut('template',tf);if(kf)await dbPut('kaefer',await readDataUrl(kf));if(gf)await dbPut('gerdau',await readDataUrl(gf));await dbPut('auto',$('autoTemplate').value);$('persistBadge').textContent='Salva neste dispositivo';log('Configuração local salva.','ok');await loadLocalConfig(true)}
async function loadLocalConfig(silent=false){try{const auto=await dbGet('auto');if(auto)$('autoTemplate').value=auto;const k=await dbGet('kaefer'),g=await dbGet('gerdau');if(k)S.logos.kaefer=k;if(g)S.logos.gerdau=g;const tf=await dbGet('template');if(tf&&$('autoTemplate').value==='yes'&&(!S.twb||!silent)){S.template=await tf.arrayBuffer();S.twb=new ExcelJS.Workbook();await S.twb.xlsx.load(S.template);$('templateName').textContent='Modelo padrão salvo neste dispositivo';$('templateName').classList.remove('hidden');$('templateBadge').textContent='Modelo salvo';$('templateBadge').className='badge';setSelect($('templateSheet'),S.twb.worksheets.map(w=>w.name));$('templateSheet').disabled=false;S.tSheet=S.twb.worksheets[0];detectTargets();renderMap()}if(auto||tf||k||g)$('persistBadge').textContent='Configurada';if(!silent&&tf)log('Modelo padrão carregado automaticamente.','ok')}catch(e){if(!silent)log('Não foi possível carregar a configuração local: '+e.message,'warn')}}
async function clearLocalConfig(){await dbClear();S.logos.kaefer=null;S.logos.gerdau=null;$('persistBadge').textContent='Não configurado';log('Configuração local apagada.','ok')}

const $=id=>document.getElementById(id);const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function log(t,c=''){const e=document.createElement('div');e.className=c;e.textContent='› '+t;$('log').appendChild(e);$('log').scrollTop=$('log').scrollHeight}
function status(t,ok=false){$('status').textContent=t;$('dot').className='dot'+(ok?' ok':'')}
function fmt(v){if(v instanceof Date){const d=v;return String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear()}return String(v??'')}
function readDataUrl(file){return new Promise((resolve,reject)=>{if(!file)return resolve(null);const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
function cellPosition(address){const m=String(address||'A1').toUpperCase().match(/^([A-Z]+)(\\d+)$/);if(!m)return{col:0,row:0};let col=0;for(const ch of m[1])col=col*26+(ch.charCodeAt(0)-64);return{col:col-1,row:Number(m[2])-1}}
function addLogo(wb,ws,data,address,width=150,height=48){if(!data)return;const ext=data.startsWith('data:image/jpeg')?'jpeg':'png';const id=wb.addImage({base64:data,extension:ext});const p=cellPosition(address);ws.addImage(id,{tl:{col:p.col,row:p.row},ext:{width,height}})}

function setSelect(el,items){el.innerHTML='';items.forEach(x=>{const o=document.createElement('option');o.value=x;o.textContent=x;el.appendChild(o)})}
function drop(id,input){const d=$(id);['dragenter','dragover'].forEach(ev=>d.addEventListener(ev,e=>{e.preventDefault();e.stopPropagation();d.classList.add('drag')}));['dragleave','dragend'].forEach(ev=>d.addEventListener(ev,e=>{e.preventDefault();d.classList.remove('drag')}));d.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();d.classList.remove('drag');const f=e.dataTransfer?.files?.[0];if(!f)return;try{const dt=new DataTransfer();dt.items.add(f);input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}))}catch(err){log('Não foi possível usar o arquivo arrastado. Clique em Selecionar arquivo.','warn')}})}
$('saveLocal').onclick=()=>saveLocalConfig();$('clearLocal').onclick=()=>clearLocalConfig();loadLocalConfig();
drop('sourceDrop',$('source'));drop('templateDrop',$('template'));
$('defaultKaefer').onchange=async e=>{if(e.target.files[0]){S.logos.kaefer=await readDataUrl(e.target.files[0]);$('persistBadge').textContent='Alterações pendentes'}};$('defaultGerdau').onchange=async e=>{if(e.target.files[0]){S.logos.gerdau=await readDataUrl(e.target.files[0]);$('persistBadge').textContent='Alterações pendentes'}};$('defaultTemplate').onchange=async e=>{if(e.target.files[0])$('persistBadge').textContent='Alterações pendentes'};
async function handleSourceFile(f){if(!f)return;const name=f.name||'arquivo';$('sourceName').textContent='📄 '+name;$('sourceName').classList.remove('hidden');$('sourceBadge').textContent='Lendo...';$('sourceBadge').className='badge warn';status('Lendo Planilha 01...');try{const buf=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('Falha ao ler o arquivo'));r.readAsArrayBuffer(f)});S.source=buf;S.swb=XLSX.read(new Uint8Array(buf),{type:'array',cellDates:true,raw:false});if(!S.swb.SheetNames?.length)throw new Error('O arquivo não possui abas válidas.');$('sourceBadge').textContent='Carregada';$('sourceBadge').className='badge';setSelect($('sourceSheet'),S.swb.SheetNames);$('sourceSheet').disabled=false;fillHeaderOptions();autoHeader();parse();log('Planilha 01 carregada: '+name,'ok');status('Planilha 01 carregada',true)}catch(err){$('sourceBadge').textContent='Erro';$('sourceBadge').className='badge warn';log('Falha ao ler Planilha 01: '+(err?.message||err),'err');status('Erro ao ler Planilha 01')}}
$('source').onchange=e=>handleSourceFile(e.target.files?.[0]);
async function handleTemplateFile(f){if(!f)return;const name=f.name||'modelo.xlsx';$('templateName').textContent='📄 '+name;$('templateName').classList.remove('hidden');$('templateBadge').textContent='Lendo...';$('templateBadge').className='badge warn';status('Lendo Planilha 02...');try{const buf=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error||new Error('Falha ao ler o arquivo'));r.readAsArrayBuffer(f)});S.template=buf;S.twb=new ExcelJS.Workbook();await S.twb.xlsx.load(buf);if(!S.twb.worksheets.length)throw new Error('O modelo não possui abas válidas.');$('templateBadge').textContent='Carregada';$('templateBadge').className='badge';setSelect($('templateSheet'),S.twb.worksheets.map(w=>w.name));$('templateSheet').disabled=false;S.tSheet=S.twb.worksheets[0];detectTargets();renderMap();log('Modelo oficial carregado: '+name,'ok');status(S.swb?'Arquivos carregados':'Modelo carregado',!!S.swb)}catch(err){$('templateBadge').textContent='Erro';$('templateBadge').className='badge warn';log('Falha ao ler o modelo XLSX: '+(err?.message||err),'err');status('Erro ao ler Planilha 02')}}
$('template').onchange=e=>handleTemplateFile(e.target.files?.[0]);
$('sourceSheet').onchange=()=>{autoHeader();parse()};$('headerRow').onchange=parse;$('templateSheet').onchange=()=>{S.tSheet=S.twb.getWorksheet($('templateSheet').value);detectTargets();renderMap()};
function fillHeaderOptions(){const s=$('headerRow');s.innerHTML='';for(let i=1;i<=60;i++){const o=document.createElement('option');o.value=i;o.textContent='Linha '+i;s.appendChild(o)}s.disabled=false}
function autoHeader(){const ws=S.swb?.Sheets[$('sourceSheet').value];if(!ws)return;const m=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});let best=0,score=-1;for(let r=0;r<Math.min(40,m.length);r++){const vals=m[r].map(norm);const sc=FIELDS.reduce((n,f)=>n+(vals.some(v=>f.a.includes(v))?1:0),0);if(sc>score){score=sc;best=r}}$('headerRow').value=best+1}
function parse(){if(!S.swb)return;const ws=S.swb.Sheets[$('sourceSheet').value];const m=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});const hr=Number($('headerRow').value||1)-1;S.headers=(m[hr]||[]).map((v,i)=>String(v??'').trim()||('Coluna '+(i+1)));const allRows=m.slice(hr+1).filter(r=>r.some(v=>String(v??'').trim()!==''));autoMap();const numeroCol=S.map.numero??-1;S.rows=allRows.filter(r=>{if(numeroCol<0)return false;return String(r[numeroCol]??'').trim()!==''});renderPreview();renderMap();$('rows').textContent=S.rows.length;$('rowBadge').textContent=S.rows.length+' registros';$('sheets').textContent=S.swb.SheetNames.length;status(S.twb?'Pronto para conferência':'Planilha 01 pronta')}
function autoMap(){S.map={};for(const f of FIELDS){let i=S.headers.findIndex(h=>f.a.includes(norm(h)));if(i<0)i=S.headers.findIndex(h=>f.a.some(a=>norm(h).includes(norm(a))||norm(a).includes(norm(h))));S.map[f.k]=i}updateStats()}
function detectTargets(){if(!S.tSheet)return;const ws=S.tSheet,found={};const explicit={numero:'F4',local:'A4',informante:'D4',ord:'A7',tipo:'B7',data:'C7',potencial:'D7',descricao:'E7',acao:'F7',responsavel:'G7',previsto:'H7',realizado:'I7',status:'J7'};const isOfficial=['PLANO DE AÇÃO','PLANO DE ACAO'].some(x=>norm(ws.getCell('C1').value).includes(norm(x)));if(isOfficial||ws.columnCount<=12){for(const [k,address] of Object.entries(explicit))found[k]={data:address}}else{const wanted={ord:['ord.','ord'],tipo:['tipo de registro'],data:['data'],semana:['semana'],potencial:['potencial','severidade'],descricao:['descrição da ocorrência','descricao da ocorrencia'],acao:['plano de ação','plano de acao'],responsavel:['responsável','responsavel'],previsto:['previsto'],realizado:['realizado'],status:['status']};for(let r=1;r<=Math.min(ws.rowCount,100);r++)for(let c=1;c<=Math.min(ws.columnCount,45);c++){const v=norm(ws.getCell(r,c).value);if(!v)continue;for(const k of Object.keys(wanted)){if(found[k])continue;if(wanted[k].some(a=>v===norm(a)||v.includes(norm(a))))found[k]={header:ws.getCell(r,c).address,data:ws.getCell(r+1,c).address}}}['numero','local','informante'].forEach(k=>{const label=k==='numero'?['nº informe','n° informe','no informe']:k==='local'?['local/área','local/area']:['informante'];const cell=findLabel(label);if(cell)found[k]={data:cell}})}S.targets={...found};updateStats()}
function findLabel(labels){if(!S.tSheet)return '';for(let r=1;r<=25;r++)for(let c=1;c<=25;c++){const v=norm(S.tSheet.getCell(r,c).value);if(!labels.some(x=>v===norm(x)||v.includes(norm(x))))continue;let nextCol=c+1;try{for(const range of Object.values(S.tSheet._merges||{})){const parts=String(range).split(':');if(parts.length!==2)continue;const a=S.tSheet.getCell(parts[0]),b=S.tSheet.getCell(parts[1]);if(r>=a.row&&r<=b.row&&c>=a.col&&c<=b.col){nextCol=b.col+1;break}}}catch(e){}return S.tSheet.getCell(r,nextCol).address}return ''}
function target(k){return S.targets[k]?.data||''}
function renderMap(){const b=$('mapBody');b.innerHTML='';for(const f of FIELDS){const i=S.map[f.k]??-1;const opts='<option value="-1">— não usar —</option>'+S.headers.map((h,j)=>'<option value="'+j+'" '+(j===i?'selected':'')+'>'+esc(h)+'</option>').join('');const rule=f.k==='severidade'?'Severidade → Potencial':f.k==='lideranca'?'Não existe na tabela do modelo':'Valor direto';const tr=document.createElement('tr');tr.innerHTML='<td><b>'+f.n+'</b>'+(f.req?'<br><small>obrigatório</small>':'')+'</td><td><select data-src="'+f.k+'">'+opts+'</select></td><td><input data-dest="'+f.k+'" value="'+esc(target(f.k))+'" placeholder="Ex.: G8"></td><td>'+rule+'</td><td><span class="badge '+(i>=0?'':'warn')+'">'+(i>=0?'Reconhecido':'Não encontrado')+'</span></td>';b.appendChild(tr)}b.querySelectorAll('[data-src]').forEach(x=>x.onchange=()=>{S.map[x.dataset.src]=Number(x.value);updateStats()});b.querySelectorAll('[data-dest]').forEach(x=>x.onchange=()=>{S.targets[x.dataset.dest]={data:x.value.trim()}});updateStats()}
function updateStats(){const used=FIELDS.filter(f=>(S.map[f.k]??-1)>=0).length;$('mapped').textContent=Math.round(used/FIELDS.length*100)+'%';$('errors').textContent=FIELDS.filter(f=>f.req&&(S.map[f.k]??-1)<0).length;const ready=!!S.source&&!!S.template&&S.rows.length>0;$('validate').disabled=!ready;$('remap').disabled=!S.swb;$('generate').disabled=true;$('topGenerate').disabled=true}
function renderPreview(){const hs=S.headers.slice(0,12);$('previewHead').innerHTML='<tr>'+hs.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr>';$('previewBody').innerHTML=S.rows.slice(0,25).map(r=>'<tr>'+hs.map((_,i)=>'<td>'+esc(fmt(r[i]))+'</td>').join('')+'</tr>').join('')}
function value(row,k){const i=S.map[k];return i>=0?fmt(row[i]):''}
function mergeMaster(ws,address){try{const merges=ws._merges||{};for(const range of Object.values(merges)){const s=String(range),parts=s.split(':');if(parts.length!==2)continue;const a=ws.getCell(parts[0]),b=ws.getCell(parts[1]),x=ws.getCell(address);if(x.row>=a.row&&x.row<=b.row&&x.col>=a.col&&x.col<=b.col)return a.address}}catch(e){}return address}
function write(ws,address,val){if(!address||val==='')return;try{ws.getCell(mergeMaster(ws,address)).value=val}catch(e){log('Não foi possível preencher '+address+': '+e.message,'warn')}}
function setTipoCheckboxes(ws,t){const ato=ws.getCell('G4'),cond=ws.getCell('G5');const atoText='ATO ABAIXO DO PADRÃO';const condText='CONDIÇÃO ABAIXO DO PADRÃO';ato.value=(t.includes('ato')?'☒ ':'☐ ')+atoText;cond.value=(t.includes('condicao')?'☒ ':'☐ ')+condText;ato.alignment={...(ato.alignment||{}),horizontal:'left',vertical:'middle'};cond.alignment={...(cond.alignment||{}),horizontal:'left',vertical:'middle'}}
function validate(){if(!S.source||!S.template){log('Carregue a Planilha 01 e o modelo oficial.','err');return false}let e=[];FIELDS.filter(f=>f.req).forEach(f=>{if((S.map[f.k]??-1)<0)e.push('Campo obrigatório sem origem: '+f.n)});const seen=new Set();S.rows.forEach((r,i)=>{const n=value(r,'numero');if(!n)e.push('Linha '+(i+1)+' sem Nº do informe');else if(seen.has(n))e.push('Nº do informe duplicado: '+n);seen.add(n)});$('errors').textContent=e.length;if(e.length){e.slice(0,25).forEach(x=>log(x,'err'));if(e.length>25)log('Mais '+(e.length-25)+' problema(s).','warn');return false}log('Validação concluída: '+S.rows.length+' registro(s) prontos.','ok');$('generate').disabled=false;$('topGenerate').disabled=false;return true}
$('validate').onclick=validate;$('remap').onclick=()=>{autoMap();renderMap();log('Mapeamento automático atualizado.','ok')};
function cloneWorkbook(){return new ExcelJS.Workbook()}
function weekOf(v){if(v instanceof Date){const d=new Date(v.getFullYear(),v.getMonth(),v.getDate());const one=new Date(d.getFullYear(),0,1);return Math.ceil((((d-one)/86400000)+one.getDay()+1)/7)}const m=String(v??'').match(/(\\d{1,2})[\\/.-](\\d{1,2})[\\/.-](\\d{4})/);if(m){const d=new Date(Number(m[3]),Number(m[2])-1,Number(m[1]));if(!Number.isNaN(d.getTime())){const one=new Date(d.getFullYear(),0,1);return Math.ceil((((d-one)/86400000)+one.getDay()+1)/7)}}return ''}
function setRecord(ws,row,i){write(ws,target('numero'),value(row,'numero'));write(ws,target('local'),value(row,'local'));write(ws,target('informante'),value(row,'informante'));for(const [k,m] of Object.entries(S.targets)){if(!m?.data||['numero','local','informante','tipo'].includes(k))continue;let v=k==='potencial'?value(row,'severidade'):k==='ord'?String(i+1):k==='semana'?(value(row,'semana')||String(weekOf(row[S.map.data]))):value(row,k);write(ws,m.data,v)}if(target('tipo'))write(ws,target('tipo'),'INFORME');const t=norm(value(row,'tipo'));setTipoCheckboxes(ws,t);ws.pageSetup.printArea='A1:J8';ws.pageSetup.orientation='landscape';ws.pageSetup.paperSize=9;ws.pageSetup.fitToWidth=1;ws.pageSetup.fitToHeight=1;ws.sheetProperties.pageSetUpPr.fitToPage=true;ws.pageMargins={left:0.25,right:0.25,top:0.35,bottom:0.35,header:0.1,footer:0.1}}
function excelCss(cell){const s=cell.style||{};const font=s.font||{};const fill=s.fill||{};const border=s.border||{};const parts=[];if(font.name)parts.push('font-family:'+font.name);if(font.sz)parts.push('font-size:'+Math.max(7,Number(font.sz))+'pt');if(font.bold)parts.push('font-weight:700');if(font.italic)parts.push('font-style:italic');if(font.color?.argb)parts.push('color:#'+String(font.color.argb).slice(-6));if(fill.type==='pattern'&&fill.fgColor?.argb)parts.push('background:#'+String(fill.fgColor.argb).slice(-6));const align=s.alignment||{};if(align.horizontal)parts.push('text-align:'+({'center':'center','right':'right','left':'left','fill':'left','justify':'justify','centerContinuous':'center'}[align.horizontal]||'left'));if(align.vertical)parts.push('vertical-align:'+({'middle':'middle','center':'middle','top':'top','bottom':'bottom'}[align.vertical]||'middle'));if(align.wrapText)parts.push('white-space:normal');else parts.push('white-space:pre-wrap');const side=x=>{if(!x?.style)return'none';const width=x.style==='hair'||x.style==='thin'?'1px':x.style==='medium'||x.style==='thick'?'2px':'1px';const color=x.color?.argb?'#'+String(x.color.argb).slice(-6):'#222';const style=(x.style==='dashed'?'dashed':x.style==='dotted'?'dotted':'solid');return width+' '+style+' '+color};parts.push('border-top:'+side(border.top),'border-right:'+side(border.right),'border-bottom:'+side(border.bottom),'border-left:'+side(border.left));return parts.join(';')}

function getPdfBounds(ws){return{minR:1,minC:1,maxR:9,maxC:10}}

function cellText(v){if(v===null||v===undefined)return'';if(typeof v==='string'||typeof v==='number'||typeof v==='boolean')return String(v);if(v.richText)return v.richText.map(x=>x.text||'').join('');if(v.result!==undefined)return String(v.result??'');if(v.text!==undefined)return String(v.text??'');if(v.formula!==undefined)return String(v.result??v.formula??'');return''}

function renderWorksheetHTML(ws){const {minR,minC,maxR,maxC}=getPdfBounds(ws);const colWidths=[];for(let c=minC;c<=maxC;c++)colWidths.push((ws.getColumn(c).width||10)*7);let html='<div class="pdfsheet"><table style="border-collapse:collapse;table-layout:fixed;width:'+colWidths.reduce((a,b)=>a+b,0)+'px"><colgroup>'+colWidths.map(w=>'<col style="width:'+w+'px">').join('')+'</colgroup><tbody>';const covered=new Set();for(const range of Object.values(ws._merges||{})){const p=String(range).split(':');if(p.length!==2)continue;const a=ws.getCell(p[0]),b=ws.getCell(p[1]);if(b.row<minR||a.row>maxR||b.col<minC||a.col>maxC)continue;for(let r=Math.max(a.row,minR);r<=Math.min(b.row,maxR);r++)for(let c=Math.max(a.col,minC);c<=Math.min(b.col,maxC);c++)if(!(r===a.row&&c===a.col))covered.add(r+':'+c)}for(let r=minR;r<=maxR;r++){const rh=(ws.getRow(r).height||15)*96/72;html+='<tr style="height:'+rh+'px">';for(let c=minC;c<=maxC;c++){if(covered.has(r+':'+c))continue;const cell=ws.getCell(r,c);let colspan=1,rowspan=1;for(const range of Object.values(ws._merges||{})){const p=String(range).split(':');if(p.length!==2)continue;const a=ws.getCell(p[0]),b=ws.getCell(p[1]);if(a.row===r&&a.col===c&&b.row<=maxR&&b.col<=maxC){colspan=b.col-a.col+1;rowspan=b.row-a.row+1;break}}const v=cellText(cell.value);html+='<td '+(colspan>1?'colspan="'+colspan+'" ':'')+(rowspan>1?'rowspan="'+rowspan+'" ':'')+'style="'+excelCss(cell)+';height:'+rh*rowspan+'px">'+esc(v)+'</td>'}html+='</tr>'}return html+'</tbody></table></div>'}
function pdfPageCSS(){return '.pdfsheet{background:#fff;padding:0;margin:0;display:inline-block}.pdfsheet table{font-family:Arial,sans-serif;font-size:10px}.pdfsheet td{box-sizing:border-box;overflow:hidden;padding:3px}.pdfsheet td:empty{padding:0}'}
async function createPdf(records){if(!window.jspdf)return null;const {jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:'landscape',unit:'pt',format:'a4',compress:true});const holder=document.createElement('div');holder.style.cssText='position:fixed;left:-100000px;top:0;background:#fff;z-index:-1';document.body.appendChild(holder);const style=document.createElement('style');style.textContent=pdfPageCSS();holder.appendChild(style);for(let i=0;i<records.length;i++){const wb=new ExcelJS.Workbook();await wb.xlsx.load(S.template);S.currentWb=wb;const ws=wb.getWorksheet(S.tSheet?.name||wb.worksheets[0].name);setRecord(ws,records[i],i);holder.innerHTML='<style>'+pdfPageCSS()+'</style>'+renderWorksheetHTML(ws);const sheet=holder.querySelector('.pdfsheet');const canvas=await html2canvas(sheet,{scale:2.2,backgroundColor:'#fff',logging:false,useCORS:true});const ratio=Math.min(806/canvas.width,560/canvas.height);const w=canvas.width*ratio,h=canvas.height*ratio;if(i>0)pdf.addPage();pdf.addImage(canvas.toDataURL('image/jpeg',.95),'JPEG',(841.89-w)/2,(595.28-h)/2,w,h);$('progress').textContent=(i+1)+'/'+records.length+' processados (PDF)'}holder.remove();return pdf.output('blob')}
async function generate(){if(!validate())return;const wantI=$('outIndividual').checked,wantC=$('outConsolidated').checked,wantP=$('outPdf').checked;if(!wantI&&!wantC&&!wantP){log('Selecione pelo menos um formato de saída.','err');return}const zip=new JSZip(),base=new Uint8Array(S.template),master=wantC?new ExcelJS.Workbook():null;$('generate').disabled=true;$('topGenerate').disabled=true;for(let i=0;i<S.rows.length;i++){const row=S.rows[i];try{const wb=new ExcelJS.Workbook();await wb.xlsx.load(base);S.currentWb=wb;const ws=wb.getWorksheet(S.tSheet?.name||wb.worksheets[0].name);setRecord(ws,row,i);const buf=await wb.xlsx.writeBuffer();const name=safe('Informe_'+value(row,'numero')+'_'+value(row,'tipo'))+'.xlsx';if(wantI)zip.file(name,buf);if(master){const mw=master.addWorksheet(safe('Informe '+value(row,'numero')).slice(0,31));for(let cc=1;cc<=ws.columnCount;cc++){mw.getColumn(cc).width=ws.getColumn(cc).width}for(let rr=1;rr<=ws.rowCount;rr++){mw.getRow(rr).height=ws.getRow(rr).height;for(let cc=1;cc<=ws.columnCount;cc++){const src=ws.getCell(rr,cc),dst=mw.getCell(rr,cc);dst.value=src.value;dst.style=JSON.parse(JSON.stringify(src.style||{}));if(src.numFmt)dst.numFmt=src.numFmt}}for(const range of Object.values(ws._merges||{})){try{mw.mergeCells(String(range))}catch(e){}}}$('progress').textContent=(i+1)+'/'+S.rows.length+' processados';if(i===0)log('Primeiro informe gerado: '+name,'ok')}catch(err){log('Erro no informe '+value(row,'numero')+': '+err.message,'err')}}if(master){const buf=await master.xlsx.writeBuffer();zip.file('Planos_de_Acao_Consolidado.xlsx',buf)}if(wantP){log('Montando PDF consolidado — 1 informe por página...','warn');const pdf=await createPdf(S.rows);if(pdf)zip.file('Planos_de_Acao_Consolidado.pdf',pdf)}const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});download(blob,'Planos_de_Acao_'+new Date().toISOString().slice(0,10)+'.zip');log('Lote concluído: '+S.rows.length+' informe(s).','ok');$('generate').disabled=false;$('topGenerate').disabled=false;status('Lote concluído',true)}
function safe(s){return String(s||'Informe').replace(/[\\/:*?"<>|]+/g,'-').replace(/\s+/g,'_').slice(0,100)}function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function config(){return {version:1,map:S.map,targets:S.targets,sourceSheet:$('sourceSheet').value,headerRow:$('headerRow').value,templateSheet:$('templateSheet').value}}
$('saveCfg').onclick=()=>download(new Blob([JSON.stringify(config(),null,2)],{type:'application/json'}),'informes-config.json');$('loadCfg').onclick=()=>$('cfgFile').click();$('cfgFile').onchange=async e=>{try{const c=JSON.parse(await e.target.files[0].text());if(c.map)S.map=c.map;if(c.targets)S.targets=c.targets;if(c.sourceSheet&&S.swb){$('sourceSheet').value=c.sourceSheet;autoHeader();$('headerRow').value=c.headerRow||1;parse()}if(c.templateSheet&&S.twb){$('templateSheet').value=c.templateSheet;S.tSheet=S.twb.getWorksheet(c.templateSheet);detectTargets()}renderMap();log('Configuração importada.','ok')}catch(err){log('Configuração inválida: '+err.message,'err')}};
$('generate').onclick=generate;$('topGenerate').onclick=generate;$('reset').onclick=()=>location.reload();