const FIELDS=[
 {k:'numero',n:'Nº do informe',a:['nº do informe','no do informe','n do informe','numero do informe','nº informe'],req:true},
 {k:'tipo',n:'Tipo de registro',a:['tipo de registro','tipo registro'],req:true},
 {k:'local',n:'Local/Área',a:['local/área','local/area','local','área','area'],req:true},
 {k:'data',n:'Data',a:['data','data do registro','data ocorrência','data da ocorrência'],req:true},
 {k:'informante',n:'Informante',a:['informante','nome do informante'],req:true},
 {k:'descricao',n:'Descrição da ocorrência',a:['descrição da ocorrência','descricao da ocorrência','descrição','descricao'],req:true},
 {k:'acao',n:'Plano de ação',a:['plano de ação','plano de acao','ação','acao']},
 {k:'responsavel',n:'Responsável',a:['responsável','responsavel']},
 {k:'lideranca',n:'Liderança',a:['liderança','lideranca']},
 {k:'severidade',n:'Severidade / Potencial',a:['severidade','potencial','potencialidade']},
 {k:'previsto',n:'Previsto',a:['previsto','data prevista','prazo']},
 {k:'realizado',n:'Realizado',a:['realizado','data realizado','data de realização']},
 {k:'status',n:'Status',a:['status','situação','situacao']}
];
const S={source:null,template:null,swb:null,twb:null,rows:[],headers:[],map:{},targets:{},tSheet:null};
const $=id=>document.getElementById(id);const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function log(t,c=''){const e=document.createElement('div');e.className=c;e.textContent='› '+t;$('log').appendChild(e);$('log').scrollTop=$('log').scrollHeight}
function status(t,ok=false){$('status').textContent=t;$('dot').className='dot'+(ok?' ok':'')}
function fmt(v){return v instanceof Date?v.toLocaleDateString('pt-BR'):String(v??'')}
function setSelect(el,items){el.innerHTML='';items.forEach(x=>{const o=document.createElement('option');o.value=x;o.textContent=x;el.appendChild(o)})}
function drop(id,input){const d=$(id);d.addEventListener('dragover',e=>{e.preventDefault();d.classList.add('drag')});d.addEventListener('dragleave',()=>d.classList.remove('drag'));d.addEventListener('drop',e=>{e.preventDefault();d.classList.remove('drag');if(e.dataTransfer.files[0]){const dt=new DataTransfer();dt.items.add(e.dataTransfer.files[0]);input.files=dt.files;input.dispatchEvent(new Event('change'))}})}
$('sourceBtn').onclick=()=>$('source').click();$('templateBtn').onclick=()=>$('template').click();drop('sourceDrop',$('source'));drop('templateDrop',$('template'));
$('source').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{S.source=await f.arrayBuffer();S.swb=XLSX.read(new Uint8Array(S.source),{type:'array',cellDates:true,raw:false});$('sourceName').textContent=f.name;$('sourceName').classList.remove('hidden');$('sourceBadge').textContent='Carregada';$('sourceBadge').className='badge';setSelect($('sourceSheet'),S.swb.SheetNames);$('sourceSheet').disabled=false;fillHeaderOptions();autoHeader();parse();log('Planilha 01 carregada: '+f.name,'ok');status('Planilha 01 carregada')}catch(err){log('Falha ao ler Planilha 01: '+err.message,'err')}};
$('template').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{S.template=await f.arrayBuffer();S.twb=new ExcelJS.Workbook();await S.twb.xlsx.load(S.template);$('templateName').textContent=f.name;$('templateName').classList.remove('hidden');$('templateBadge').textContent='Carregada';$('templateBadge').className='badge';setSelect($('templateSheet'),S.twb.worksheets.map(w=>w.name));$('templateSheet').disabled=false;S.tSheet=S.twb.worksheets[0];detectTargets();renderMap();log('Modelo oficial carregado: '+f.name,'ok');status(S.swb?'Arquivos carregados':'Modelo carregado',!!S.swb)}catch(err){log('Falha ao ler o modelo XLSX: '+err.message,'err')}};
$('sourceSheet').onchange=()=>{autoHeader();parse()};$('headerRow').onchange=parse;$('templateSheet').onchange=()=>{S.tSheet=S.twb.getWorksheet($('templateSheet').value);detectTargets();renderMap()};
function fillHeaderOptions(){const s=$('headerRow');s.innerHTML='';for(let i=1;i<=60;i++){const o=document.createElement('option');o.value=i;o.textContent='Linha '+i;s.appendChild(o)}s.disabled=false}
function autoHeader(){const ws=S.swb?.Sheets[$('sourceSheet').value];if(!ws)return;const m=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});let best=0,score=-1;for(let r=0;r<Math.min(40,m.length);r++){const vals=m[r].map(norm);const sc=FIELDS.reduce((n,f)=>n+(vals.some(v=>f.a.includes(v))?1:0),0);if(sc>score){score=sc;best=r}}$('headerRow').value=best+1}
function parse(){if(!S.swb)return;const ws=S.swb.Sheets[$('sourceSheet').value];const m=XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});const hr=Number($('headerRow').value||1)-1;S.headers=(m[hr]||[]).map((v,i)=>String(v||'').trim()||('Coluna '+(i+1)));S.rows=m.slice(hr+1).filter(r=>r.some(v=>String(v??'').trim()!==''));autoMap();renderPreview();renderMap();$('rows').textContent=S.rows.length;$('rowBadge').textContent=S.rows.length+' registros';$('sheets').textContent=S.swb.SheetNames.length;status(S.twb?'Pronto para conferência':'Planilha 01 pronta')}
function autoMap(){S.map={};for(const f of FIELDS){let i=S.headers.findIndex(h=>f.a.includes(norm(h)));if(i<0)i=S.headers.findIndex(h=>f.a.some(a=>norm(h).includes(norm(a))||norm(a).includes(norm(h))));S.map[f.k]=i}updateStats()}
function detectTargets(){if(!S.tSheet)return;const ws=S.tSheet,found={};const wanted={ord:['ord.','ord'],tipo:['tipo de registro'],data:['data'],potencial:['potencial','severidade'],descricao:['descrição da ocorrência','descricao da ocorrencia'],acao:['plano de ação','plano de acao'],responsavel:['responsável','responsavel'],previsto:['previsto'],realizado:['realizado'],status:['status']};for(let r=1;r<=Math.min(ws.rowCount,100);r++)for(let c=1;c<=Math.min(ws.columnCount,45);c++){const v=norm(ws.getCell(r,c).value);if(!v)continue;for(const k of Object.keys(wanted)){if(found[k])continue;if(wanted[k].some(a=>v===norm(a)||v.includes(norm(a))))found[k]={header:ws.getCell(r,c).address,data:ws.getCell(r+1,c).address}}}S.targets={...found};['numero','local','informante'].forEach(k=>{const label=k==='numero'?['nº informe','n° informe','no informe']:k==='local'?['local/área','local/area']:['informante'];const cell=findLabel(label);if(cell)S.targets[k]={data:cell}});updateStats()}
function findLabel(labels){if(!S.tSheet)return '';for(let r=1;r<=25;r++)for(let c=1;c<=25;c++){const v=norm(S.tSheet.getCell(r,c).value);if(labels.some(x=>v===norm(x)||v.includes(norm(x))))return S.tSheet.getCell(r,c+1).address}return ''}
function target(k){return S.targets[k]?.data||''}
function renderMap(){const b=$('mapBody');b.innerHTML='';for(const f of FIELDS){const i=S.map[f.k]??-1;const opts='<option value="-1">— não usar —</option>'+S.headers.map((h,j)=>'<option value="'+j+'" '+(j===i?'selected':'')+'>'+esc(h)+'</option>').join('');const rule=f.k==='severidade'?'Severidade → Potencial':f.k==='lideranca'?'Não existe na tabela do modelo':'Valor direto';const tr=document.createElement('tr');tr.innerHTML='<td><b>'+f.n+'</b>'+(f.req?'<br><small>obrigatório</small>':'')+'</td><td><select data-src="'+f.k+'">'+opts+'</select></td><td><input data-dest="'+f.k+'" value="'+esc(target(f.k))+'" placeholder="Ex.: G8"></td><td>'+rule+'</td><td><span class="badge '+(i>=0?'':'warn')+'">'+(i>=0?'Reconhecido':'Não encontrado')+'</span></td>';b.appendChild(tr)}b.querySelectorAll('[data-src]').forEach(x=>x.onchange=()=>{S.map[x.dataset.src]=Number(x.value);updateStats()});b.querySelectorAll('[data-dest]').forEach(x=>x.onchange=()=>{S.targets[x.dataset.dest]={data:x.value.trim()}});updateStats()}
function updateStats(){const used=FIELDS.filter(f=>(S.map[f.k]??-1)>=0).length;$('mapped').textContent=Math.round(used/FIELDS.length*100)+'%';$('errors').textContent=FIELDS.filter(f=>f.req&&(S.map[f.k]??-1)<0).length;const ready=!!S.source&&!!S.template&&S.rows.length>0;$('validate').disabled=!ready;$('remap').disabled=!S.swb;$('generate').disabled=true;$('topGenerate').disabled=true}
function renderPreview(){const hs=S.headers.slice(0,12);$('previewHead').innerHTML='<tr>'+hs.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr>';$('previewBody').innerHTML=S.rows.slice(0,25).map(r=>'<tr>'+hs.map((_,i)=>'<td>'+esc(fmt(r[i]))+'</td>').join('')+'</tr>').join('')}
function value(row,k){const i=S.map[k];return i>=0?fmt(row[i]):''}
function mergeMaster(ws,address){try{const merges=ws._merges||{};for(const range of Object.values(merges)){const s=String(range),parts=s.split(':');if(parts.length!==2)continue;const a=ws.getCell(parts[0]),b=ws.getCell(parts[1]),x=ws.getCell(address);if(x.row>=a.row&&x.row<=b.row&&x.col>=a.col&&x.col<=b.col)return a.address}}catch(e){}return address}
function write(ws,address,val){if(!address||val==='')return;try{ws.getCell(mergeMaster(ws,address)).value=val}catch(e){log('Não foi possível preencher '+address+': '+e.message,'warn')}}
function checkbox(ws,kind){const wanted=kind==='ato'?'ato abaixo do padrao':'condicao abaixo do padrao';for(let r=1;r<=25;r++)for(let c=1;c<=25;c++){const v=norm(ws.getCell(r,c).value);if(v===wanted||v.includes(wanted)){const candidates=[[r,c-1],[r,c+1],[r+1,c],[r-1,c]];for(const [rr,cc] of candidates){if(rr>0&&cc>0){const cell=ws.getCell(rr,cc);if(cell.value==null||cell.value===''){cell.value='☒';return}}}}}}
function validate(){if(!S.source||!S.template){log('Carregue a Planilha 01 e o modelo oficial.','err');return false}let e=[];FIELDS.filter(f=>f.req).forEach(f=>{if((S.map[f.k]??-1)<0)e.push('Campo obrigatório sem origem: '+f.n)});const seen=new Set();S.rows.forEach((r,i)=>{const n=value(r,'numero');if(!n)e.push('Linha '+(i+1)+' sem Nº do informe');else if(seen.has(n))e.push('Nº do informe duplicado: '+n);seen.add(n)});$('errors').textContent=e.length;if(e.length){e.slice(0,25).forEach(x=>log(x,'err'));if(e.length>25)log('Mais '+(e.length-25)+' problema(s).','warn');return false}log('Validação concluída: '+S.rows.length+' registro(s) prontos.','ok');$('generate').disabled=false;$('topGenerate').disabled=false;return true}
$('validate').onclick=validate;$('remap').onclick=()=>{autoMap();renderMap();log('Mapeamento automático atualizado.','ok')};
async function generate(){if(!validate())return;const zip=new JSZip(),base=new Uint8Array(S.template);$('generate').disabled=true;$('topGenerate').disabled=true;for(let i=0;i<S.rows.length;i++){const row=S.rows[i];try{const wb=new ExcelJS.Workbook();await wb.xlsx.load(base);const ws=wb.getWorksheet(S.tSheet?.name||wb.worksheets[0].name);write(ws,target('numero'),value(row,'numero'));write(ws,target('local'),value(row,'local'));write(ws,target('informante'),value(row,'informante'));for(const [k,m] of Object.entries(S.targets)){if(!m?.data||['numero','local','informante'].includes(k))continue;write(ws,m.data,k==='potencial'?value(row,'severidade'):k==='ord'?String(i+1):value(row,k))}const t=norm(value(row,'tipo'));if(t.includes('ato'))checkbox(ws,'ato');if(t.includes('condicao'))checkbox(ws,'condicao');const buf=await wb.xlsx.writeBuffer();const name=safe('Informe_'+value(row,'numero')+'_'+value(row,'tipo'))+'.xlsx';zip.file(name,buf);log('Gerado '+(i+1)+'/'+S.rows.length+': '+name,'ok')}catch(err){log('Erro no informe '+value(row,'numero')+': '+err.message,'err')}}const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});download(blob,'Informes_Plano_de_Acao.zip');log('ZIP finalizado.','ok');$('generate').disabled=false;$('topGenerate').disabled=false;status('Geração concluída',true)}
function safe(s){return String(s||'Informe').replace(/[\\/:*?"<>|]+/g,'-').replace(/\s+/g,'_').slice(0,100)}function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000)}
function config(){return {version:1,map:S.map,targets:S.targets,sourceSheet:$('sourceSheet').value,headerRow:$('headerRow').value,templateSheet:$('templateSheet').value}}
$('saveCfg').onclick=()=>download(new Blob([JSON.stringify(config(),null,2)],{type:'application/json'}),'informes-config.json');$('loadCfg').onclick=()=>$('cfgFile').click();$('cfgFile').onchange=async e=>{try{const c=JSON.parse(await e.target.files[0].text());if(c.map)S.map=c.map;if(c.targets)S.targets=c.targets;if(c.sourceSheet&&S.swb){$('sourceSheet').value=c.sourceSheet;autoHeader();$('headerRow').value=c.headerRow||1;parse()}if(c.templateSheet&&S.twb){$('templateSheet').value=c.templateSheet;S.tSheet=S.twb.getWorksheet(c.templateSheet);detectTargets()}renderMap();log('Configuração importada.','ok')}catch(err){log('Configuração inválida: '+err.message,'err')}};
$('generate').onclick=generate;$('topGenerate').onclick=generate;$('reset').onclick=()=>location.reload();